### ISSUE TITLE
Pool does not contain 68369

### ISSUE THREAD

**Issue by Sashweed** [kelesi/mtga-utils#1]
Amazing tool, Thanks.

I am getting this error however it does appear to still export

C:\Users\User\Downloads>mtga-export.exe --goldfish -f mtga_collection_goldfish.csv
Unknown card in collection: Pool does not contain 68369 (Try to update the mtga module)
Exported to file

Thanks again.

**Comment by kelesi** [comment]
Thanks for reporting.
Seems like this card id is not defined in the module I depend on. I will try to fix it on my end. 
Do you get this error only for this one card?

**Comment by kelesi** [comment]
The latest windows release was updated to cover id 68369. Pull request for python-mtga is pending (https://github.com/mtgatracker/python-mtga/pull/7)

**Comment by Sashweed** [comment]
I'm not 100% sure which card it is... I had just bought several hundred packs but it looks like you might have fixed it anyway. I'll download and try again.

J

**Comment by kelesi** [comment]
I also improved the script to fetch unknown cards from scryfall.com. If you get any error, please let me know.
