### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by Kreyren** [kelesi/mtga-utils#11]
Assuming it beeing written in python could you export release for linux? :thinking:

**Comment by kelesi** [comment]
Could you please elaborate?
In Linux you can just download the code and run it (assuming installed dependencies).
Or are you talking about a package for PyPi?

**Comment by Kreyren** [comment]
@kelesi It's expected to run your code same way as windows version assuming MTGA running on platinum using wine, so providing executable in releases and some official support from you would be great.

**Comment by kelesi** [comment]
I am sorry, what is platinum?
If you are running MTGA in wine, the windows executable should work also in wine.
You can also use just the python script. Python scripts are executables.
I am not sure what you need. The windows executable is just for non-tech-savvy people who don't know how to install python in windows.

**Comment by Kreyren** [comment]
> I am sorry, what is platinum?

Meaning that the game runs same or better on wine

> You can also use just the python script. Python scripts are executables.

I know, but you are providing master version only or is this rolling release?

**Comment by kelesi** [comment]
Master is the latest code.

**Comment by Kreyren** [comment]
fair enough
