### ISSUE TITLE
About Custom Exports

### ISSUE THREAD

**Issue by valdeniomarinho** [kelesi/mtga-utils#12]
I noticed that isnt possible to parse a "custom character" through parameter [-e]. It should be good to be able to. For example: .\mtga-export.exe -e count customChar pretty_name -f output.txt
where this customChar can be any character choosed by user, by doing this we can build more custom output formats.

a bit more, below here is just a guess of mine...

input:
.\mtga-export.exe -e count customChar_# pretty_name -f output.txt

output:
3#Pretty Name

**Comment by kelesi** [comment]
You can easily achieve this with tr, sed, awk or other standard linux command line tools.
Example:
`mtga-export.py -e count pretty_name | tr "," "#" > output.txt`

On windows you can do:
`mtga-export.exe -e count pretty_name -f output.txt`
`powershell -command "(get-content output.txt) -replace ',', '#'" > output2.txt`
