### ISSUE TITLE
MTGA 1678.727490 breaks log file parsing

### ISSUE THREAD

**Issue by pak21** [kelesi/mtga-utils#14]
It seems that MTGA 1678.727490 (the 2019-09-04 release) breaks the log file parsing. Attached are:

* The [splash screen](https://user-images.githubusercontent.com/129235/64384954-0e63b800-d02e-11e9-8847-9a48e4bc6650.png), just so we know we're talking about the same version.
* [A log file from starting the game, giving Sparky a beatdown and quitting](https://github.com/kelesi/mtga-utils/files/3581331/output_log-SparkyBeatdown.txt).
  * There what looks like a deck list in here but not the whole collection? If it's the deck I was using, it's a Temur Elementals (Risen Reef / Omnath, Locus of the Roil) deck.
* [A log file from starting the game, browsing to Decks / Collection and quitting](https://github.com/kelesi/mtga-utils/files/3581332/output_log-DecksCollection.txt). Doesn't look like there's anything at all useful in this file.

Let me know if there's any other useful information I can gather, but my gut feel is that we're out of luck here :-(

**Comment by pak21** [comment]
Ah ha, seems there's an option to renable detailed logging - see e.g. "9/4 Arena Update Logging Issue" at [Daily Arena](https://www.dailyarena.net/2019/09/06/daily-arena-deck-advisor-v-1-0-3-1/).

**Comment by kelesi** [comment]
Thank you for figuring this out. I was a bit afraid they completely removed the logging of the collection.
I will give it a try.

**Comment by pak21** [comment]
Seems to be working in my testing. I almost think of this as good, it that WotC calling the option "plugin support" implies they're aware of and not deliberately trying to break all the tools out there which do use the log file - which hopefully means they're less likely to break it in the future. I'll close this issue, I'd suggest opening a new issue if there are any subtle failures with the new version.
