### ISSUE TITLE
Log file format changed in 2019-11-21 patch

### ISSUE THREAD

**Issue by pak21** [kelesi/mtga-utils#19]
The 2019-11-21 patch to the client has changed the log file format so that the whole JSON response is on one line, rather than containing newlines:

    [UnityCrossThreadLogger]<== PlayerInventory.GetPlayerCardsV3 {"id":15,"payload":{"69110":2,"70094":2,...,"70395":1}}
 
(response clipped for clarity). This breaks the logfile parsing... it should actually make the parsing easier as we can throw away that clunky brace counting.

I'll try and come up with a patch in the next couple of days if you don't get one in first :-)

**Comment by kelesi** [comment]
I changed the code to work for both the old and new log versions.
One small seemingly unrelated issue popped up though.

This should return a card object, but returns a string:
`>>> all_mtga_cards.find_one(70361)`
`'Skewer the Critics deals 3 damage to any target.'`

Seems like a potential bug in the python-mtga. For now I am double checking if the instance is correct and issue a warning.

**Comment by kelesi** [comment]
I switched to Python 3 and latest python-mtga and the id 70361 works fine now:
```
>>> mtga.set_data.all_mtga_cards.find_one(70361)
<Card: 'Resolute Rider' ['White', 'Black'] ELD 70361>
```

**Comment by pak21** [comment]
Looks mostly good to me. One small issue I found: the keyword matching matches prefixes, so if there were two responses in the log for (say) `<== KeywordOne {"id":1,"payload":{}}` followed by `<== KeywordOneHundred {"id":2,"payload":{}}`, attempting to fetch `<== KeywordOne` fails as it attempts to parse `Hundred {"id":2,"payload":{}}` as a JSON string. Doesn't seem to affect the actual game logs for now.
