### ISSUE TITLE
MTG arena exclusives not recognised

### ISSUE THREAD

**Issue by Sashweed** [kelesi/mtga-utils#2]
Error now gone but when I import into MTG GF I get

`There were 5 warnings:

Line 116: Unknown card: 'Angelic Reward, ANA'. 
Line 330: Unknown card: 'Inspiring Commander, ANA'. 
Line 537: Unknown card: 'Spiritual Guardian, ANA'. 
Line 539: Unknown card: 'Tactical Advantage, ANA'. 
Line 715: Unknown card: 'Confront the Assault, ANA'. `

J

**Comment by kelesi** [comment]
mtggoldfish does not recognize the set "ANA". They are using "ARENA". I explicitly changed that only for mtggoldfish export. Please give it a try.

**Comment by Sashweed** [comment]
Works a treat!
