### ISSUE TITLE
Could not parse JSON

### ISSUE THREAD

**Issue by Sashweed** [kelesi/mtga-utils#20]
mtga-export.exe --goldfish -f mtga_collection_goldfish.csv
Error: Could not parse json data:  Expecting value: line 1 column 1 (char 0)
Exported to file

any ideas?

**Comment by kelesi** [comment]
Should be fixed in latest version (v0.3.1). Please check and close issue if it's working for you.

**Comment by Sashweed** [comment]
all fixed... amazing dev speed. Thank you from all users
