### ISSUE TITLE
Unknown Card in Collection & Could Not Fetch Unknown Card #2

### ISSUE THREAD

**Issue by jjdtech** [kelesi/mtga-utils#26]
Three things and it's probably me. Not sure what I'm doing wrong.  Ver 0.3.7

mtga-export.exe -c >out5.txt
WARNING:root:Could not dynamically generate card sets. Do you have Arena installed?
I'm running the latest version of Arena

I see this was an issue before.  First line looks a little strange as well.
mtga-export.exe -c >out5.txt
hit an error on 54347 / Fabled Hero / 12
69110 <Card: 'Inspiring Commander' ['White'] ANA 69110> 2
70094 <Card: 'Serra's Guardian' ['White'] M20 70094> 2
68475 <Card: 'Healer's Hawk' ['White'] GRN 68475> 4
70397 <Card: 'Plains' ['White'] ELD 70397> 1
Info: Unknown card in collection: Pool does not contain 70774 (Will fetch it from Scryfall)
Warning: Could not fetch unknown card from scryfall: Unknown card id 70774. Status code: 404
Info: Unknown card in collection: Pool does not contain 70775 (Will fetch it from Scryfall)
Warning: Could not fetch unknown card from scryfall: Unknown card id 70775. Status code: 404
Info: Unknown card in collection: Pool does not contain 70776 (Will fetch it from Scryfall)
Warning: Could not fetch unknown card from scryfall: Unknown card id 70776. Status code: 404
Info: Unknown card in collection: Pool does not contain 71234 (Will fetch it from Scryfall)
Warning: Could not fetch unknown card from scryfall: Unknown card id 71234. Status code: 404
Info: Unknown card in collection: Pool does not contain 71188 (Will fetch it from Scryfall)
Warning: Could not fetch unknown card from scryfall: Unknown card id 71188. Status code: 404

Also I'm not sure why the collids command is erroring out?
mtga-export.exe --collids
Error: Could not parse json data:  Expecting value: line 1 column 1 (char 0)
{}

**Comment by jjdtech** [comment]
This may be a new set issue.  I just noticed that my latest download of MTGJSON AllPrintings doesn't have arenaID's for IKO yet and neither does scryfall.com.

**Comment by kelesi** [comment]
Yes, this is related to tje new set. My utility uses python-mtga, in case of the bundled exe, it was an older version. Although python-mtga fetches cards from Arena preferably, but seems like this is failing (the first warning is a clear indication) and the cards are not included in the exe and seems like also not on Scryfall. 
I suppose you are running this on Windows (not Wine or similar)?

**Comment by kelesi** [comment]
Should be fixed now in v0.3.8. Please check.

**Comment by jjdtech** [comment]
Yes, I'm running it on Win10 actual not VDI or Wine on Linux.  Just easier than installing Python for what I'm doing.  
That fixed it.  Entire collection dumps without any issue.  Thank you!
