### ISSUE TITLE
hit an error on 13491 / Ancestral Mask / 229

### ISSUE THREAD

**Issue by ElLorans** [kelesi/mtga-utils#32]
It looks like the log file changed format and causes errors.

**Comment by ElLorans** [comment]
Solved with latest python-mtga from https://github.com/mtgatracker/python-mtga

**Comment by ElLorans** [comment]
The new patch changed the log format once again

**Comment by pak21** [comment]
I've opened #33 for this; I'd suggest closing this one as it's now a very different error from that in the title.

**Comment by ElLorans** [comment]
Closeed because duplicate of [#33](https://github.com/kelesi/mtga-utils/issues/33)
