### ISSUE TITLE
Unknown Card in Collection & Could Not Fetch Unknown Card Errors

### ISSUE THREAD

**Issue by seannyfunco** [kelesi/mtga-utils#5]
Reporting based on your request from Reddit. This is all I could grab but I believe there are more:
Warning: Unknown card in collection: Pool does not contain 69192 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69172 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69190 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69176 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69177 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69332 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69138 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69305 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69398 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69309 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 68412 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69303 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69338 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69333 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69331 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69337 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69334 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69298 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69232 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69318 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69251 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69208 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69209 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69205 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69201 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69140 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69144 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69131 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69252 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69207 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69392 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69397 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69241 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69246 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69244 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69248 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69145 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69142 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69346 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69344 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69348 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69395 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69147 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69187 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69379 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69266 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69267 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69391 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69188 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69185 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69186 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69181 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69180 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69285 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69263 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69326 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69206 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69239 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69238 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69231 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69237 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69235 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69158 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69156 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69406 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69304 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69302 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69202 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69203 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69173 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 68409 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69401 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69224 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69225 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69214 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69217 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69216 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69276 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69271 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69210 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69387 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69291 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69290 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69292 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69299 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69383 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69135 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 68411 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69132 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69278 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69198 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69197 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69275 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69191 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69168 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69274 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 68413 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69228 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69247 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69151 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69174 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69341 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69257 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69223 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69296 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69358 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69226 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69222 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69384 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69382 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69403 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69273 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69310 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69405 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69312 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69200 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69319 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69165 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69164 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69161 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69169 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69317 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69355 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 68410 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69313 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69268 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69260 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69261 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69329 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69287 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69284 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69141 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69280 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69322 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69324 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69289 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69219 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69215 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69211 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69781 (Trying to fetch it from Scryfall)
Warning: Could not fetch unknown card from scryfall: Unknown card id 69781. Status code: 404
Warning: Unknown card in collection: Pool does not contain 69213 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69212 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69136 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69243 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69236 (Trying to fetch it from Scryfall)
Warning: Unknown card in collection: Pool does not contain 69385 (Trying to fetch it from Scryfall)

**Comment by kelesi** [comment]
From the output, I can see that all cards were successfully fetched from Scryfall, except 69781. 
The warning is produced, when a card is not found in the python-mtga package and then fetches it from Scryfall. You can easily verify this by searching the cards in your export. 
69781 is not on Scryfall and I submitted an request to fix it.

**Comment by seannyfunco** [comment]
Got it. Will keep an eye out for any other future "Unknown card id" messages going forward. Thanks for the communication and help.

**Comment by kelesi** [comment]
Just for info, I changed the message prefix 'Warning' to 'Info'. 'Error' is used when something goes wrong and 'Warning' when a card was really not found (neither in python-mtga nor scryfall).
