### ISSUE TITLE
SetID Incorrect for Dominaria on MTGGoldFish

### ISSUE THREAD

**Issue by seannyfunco** [kelesi/mtga-utils#8]
Looks like code is using DAR for set ID instead of DOM. After importing CSV generated from MTGA-Export and importing to MTGGoldfish received the following errors when previously these cards never generated these import errors:
Line 3: Unknown card: 'Homarid Explorer, DAR'. 
Line 19: Unknown card: 'Karn, Scion of Urza, DAR'. 
Line 25: Unknown card: 'Voltaic Servant, DAR'. 
Line 27: Unknown card: 'Thran Temporal Gateway, DAR'. 
Line 34: Unknown card: 'Serra Angel, DAR'. 
Line 37: Unknown card: 'Shalai, Voice of Plenty, DAR'. 
Line 40: Unknown card: 'Tragic Poet, DAR'. 
Line 54: Unknown card: 'Thallid Soothsayer, DAR'. 
Line 55: Unknown card: 'Vodalian Arcanist, DAR'. 
Line 56: Unknown card: 'Zahid, Djinn of the Lamp, DAR'. 
Line 58: Unknown card: 'Soul Salvage, DAR'. 
Line 59: Unknown card: 'Settle the Score, DAR'. 
Line 61: Unknown card: 'Thallid Omnivore, DAR'. 
Line 64: Unknown card: 'Elfhame Druid, DAR'. 
Line 68: Unknown card: 'Yargle, Glutton of Urborg, DAR'. 
Line 71: Unknown card: 'Seismic Shift, DAR'. 
Line 72: Unknown card: 'Shivan Fire, DAR'. 
Line 73: Unknown card: 'Mesa Unicorn, DAR'. 
Line 87: Unknown card: 'Warcry Phoenix, DAR'. 
Line 114: Unknown card: 'Grand Warlord Radha, DAR'. 
Line 116: Unknown card: 'Hallar, the Firefletcher, DAR'. 
Line 119: Unknown card: 'Garna, the Bloodflame, DAR'. 
Line 123: Unknown card: 'Isolated Chapel, DAR'. 
Line 140: Unknown card: 'Curator's Ward, DAR'. 
Line 144: Unknown card: 'Primevals' Glorious Rebirth, DAR'. 
Line 146: Unknown card: 'Deep Freeze, DAR'. 
Line 149: Unknown card: 'Diligent Excavator, DAR'. 
Line 168: Unknown card: 'Immortal Phoenix, G18'. 
Line 172: Unknown card: 'Hinterland Harbor, DAR'. 
Line 173: Unknown card: 'Cloudreader Sphinx, DAR'. 
Line 174: Unknown card: 'Clifftop Retreat, DAR'. 
Line 176: Unknown card: 'Befuddle, DAR'. 
Line 178: Unknown card: 'Blink of an Eye, DAR'. 
Line 182: Unknown card: 'Memorial to Folly, DAR'. 
Line 186: Unknown card: 'Raff Capashen, Ship's Mage, DAR'. 
Line 194: Unknown card: 'Forebear's Blade, DAR'. 
Line 195: Unknown card: 'Adamant Will, DAR'. 
Line 196: Unknown card: 'Guardians of Koilos, DAR'. 
Line 200: Unknown card: 'Gift of Growth, DAR'. 
Line 202: Unknown card: 'Helm of the Host, DAR'. 
Line 208: Unknown card: 'Goblin Chainwhirler, DAR'. 
Line 209: Unknown card: 'Marwyn, the Nurturer, DAR'. 
Line 212: Unknown card: 'Goblin Warchief, DAR'. 
Line 213: Unknown card: 'Llanowar Envoy, DAR'. 
Line 215: Unknown card: 'Llanowar Elves, DAR'. 
Line 216: Unknown card: 'Jaya Ballard, DAR'. 
Line 261: Unknown card: 'Grunn, the Lonely King, DAR'. 
Line 270: Unknown card: 'Serra Disciple, DAR'. 
Line 281: Unknown card: 'Teshar, Ancestor's Apostle, DAR'. 
Line 294: Unknown card: 'Juggernaut, DAR'. 
Line 295: Unknown card: 'Howling Golem, DAR'. 
Line 296: Unknown card: 'Jousting Lance, DAR'. 
Line 297: Unknown card: 'Jhoira's Familiar, DAR'. 
Line 307: Unknown card: 'History of Benalia, DAR'. 
Line 309: Unknown card: 'Healing Grace, DAR'. 
Line 328: Unknown card: 'Unwind, DAR'. 
Line 336: Unknown card: 'Tempest Djinn, DAR'. 
Line 341: Unknown card: 'Skirk Prospector, DAR'. 
Line 343: Unknown card: 'Siege-Gang Commander, DAR'. 
Line 345: Unknown card: 'Skizzik, DAR'. 
Line 348: Unknown card: 'Pyromantic Pilgrim, DAR'. 
Line 356: Unknown card: 'Grow from the Ashes, DAR'. 
Line 376: Unknown card: 'Whisper, Blood Liturgist, DAR'. 
Line 378: Unknown card: 'Vicious Offering, DAR'. 
Line 385: Unknown card: 'Adeliz, the Cinder Wind, DAR'. 
Line 387: Unknown card: 'Yavimaya Sapherd, DAR'. 
Line 389: Unknown card: 'Wild Onslaught, DAR'. 
Line 390: Unknown card: 'Windgrace Acolyte, DAR'. 
Line 397: Unknown card: 'Torgaar, Famine Incarnate, DAR'. 
Line 414: Unknown card: 'Mammoth Spider, DAR'. 
Line 431: Unknown card: 'Memorial to Glory, DAR'. 
Line 432: Unknown card: 'Memorial to Unity, DAR'. 
Line 434: Unknown card: 'Memorial to War, DAR'. 
Line 435: Unknown card: 'Radiating Lightning, DAR'. 
Line 436: Unknown card: 'Sulfur Falls, DAR'. 
Line 439: Unknown card: 'Warlord's Fury, DAR'. 
Line 444: Unknown card: 'Aven Sentry, DAR'. 
Line 447: Unknown card: 'Kazarov, Sengir Pureblood, DAR'. 
Line 450: Unknown card: 'Blessed Light, DAR'. 
Line 451: Unknown card: 'Fungal Infection, DAR'. 
Line 452: Unknown card: 'Final Parting, DAR'. 
Line 462: Unknown card: 'Muldrotha, the Gravetide, DAR'. 
Line 465: Unknown card: 'Demonic Vigor, DAR'. 
Line 467: Unknown card: 'Demonlord Belzenlok, DAR'. 
Line 468: Unknown card: 'Orcish Vandal, DAR'. 
Line 469: Unknown card: 'Dark Bargain, DAR'. 
Line 470: Unknown card: 'Deathbloom Thallid, DAR'. 
Line 471: Unknown card: 'Keldon Raider, DAR'. 
Line 473: Unknown card: 'Keldon Warcaller, DAR'. 
Line 477: Unknown card: 'Keldon Overseer, DAR'. 
Line 495: Unknown card: 'Divination, DAR'. 
Line 520: Unknown card: 'Territorial Allosaurus, DAR'. 
Line 522: Unknown card: 'Verdant Force, DAR'. 
Line 535: Unknown card: 'Angelic Guardian, G18'. 
Line 553: Unknown card: 'Wizard's Lightning, DAR'. 
Line 554: Unknown card: 'Fire Elemental, DAR'. 
Line 565: Unknown card: 'Knight of Grace, DAR'. 
Line 567: Unknown card: 'Knight of New Benalia, DAR'. 
Line 569: Unknown card: 'Kwende, Pride of Femeref, DAR'. 
Line 586: Unknown card: 'Syncopate, DAR'. 
Line 592: Unknown card: 'The Eldest Reborn, DAR'. 
Line 598: Unknown card: 'Blessing of Belzenlok, DAR'. 
Line 604: Unknown card: 'The Flame of Keld, DAR'. 
Line 611: Unknown card: 'Navigator's Compass, DAR'. 
Line 613: Unknown card: 'Pardic Wanderer, DAR'. 
Line 614: Unknown card: 'Mishra's Self-Replicator, DAR'. 
Line 615: Unknown card: 'Danitha Capashen, Paragon, DAR'. 
Line 617: Unknown card: 'Charge, DAR'. 
Line 619: Unknown card: 'D'Avenant Trapper, DAR'. 
Line 620: Unknown card: 'Powerstone Shard, DAR'. 
Line 621: Unknown card: 'Board the Weatherlight, DAR'. 
Line 622: Unknown card: 'Ghitu Chronicler, DAR'. 
Line 623: Unknown card: 'Call the Cavalry, DAR'. 
Line 628: Unknown card: 'Gaea's Protector, DAR'. 
Line 629: Unknown card: 'Fiery Intervention, DAR'. 
Line 632: Unknown card: 'Fungal Plots, DAR'. 
Line 637: Unknown card: 'Vengeant Vampire, G18'. 
Line 645: Unknown card: 'Bloodstone Goblin, DAR'. 
Line 648: Unknown card: 'Fervent Strike, DAR'. 
Line 661: Unknown card: 'Rampaging Brontodon, G18'. 
Line 688: Unknown card: 'Chainer's Torment, DAR'. 
Line 703: Unknown card: 'Sparring Construct, DAR'. 
Line 704: Unknown card: 'Shield of the Realm, DAR'. 
Line 705: Unknown card: 'Short Sword, DAR'. 
Line 710: Unknown card: 'Feral Abomination, DAR'. 
Line 711: Unknown card: 'On Serra's Wings, DAR'. 
Line 713: Unknown card: 'Pegasus Courser, DAR'. 
Line 716: Unknown card: 'Seal Away, DAR'. 
Line 717: Unknown card: 'Dread Shade, DAR'. 
Line 718: Unknown card: 'Sergeant-at-Arms, DAR'. 
Line 719: Unknown card: 'Drudge Sentinel, DAR'. 
Line 723: Unknown card: 'Eviscerate, DAR'. 
Line 726: Unknown card: 'Rescue, DAR'. 
Line 730: Unknown card: 'Slimefoot, the Stowaway, DAR'. 
Line 732: Unknown card: 'Tatyova, Benthic Druid, DAR'. 
Line 734: Unknown card: 'Cast Down, DAR'. 
Line 735: Unknown card: 'Rite of Belzenlok, DAR'. 
Line 738: Unknown card: 'Cabal Evangel, DAR'. 
Line 743: Unknown card: 'Rat Colony, DAR'. 
Line 758: Unknown card: 'Zhalfirin Void, DAR'. 
Line 771: Unknown card: 'Adventurous Impulse, DAR'. 
Line 789: Unknown card: 'Saproling Migration, DAR'. 
Line 793: Unknown card: 'Spore Swarm, DAR'. 
Line 795: Unknown card: 'Woodland Cemetery, DAR'. 
Line 813: Unknown card: 'Angler Turtle, G18'. 
Line 828: Unknown card: 'Baloth Gorger, DAR'. 
Line 839: Unknown card: 'Ancient Animus, DAR'. 
Line 853: Unknown card: 'Triumph of Gerrard, DAR'. 
Line 857: Unknown card: 'Academy Drake, DAR'. 
Line 859: Unknown card: 'Naban, Dean of Iteration, DAR'. 
Line 861: Unknown card: 'Precognition Field, DAR'. 
Line 863: Unknown card: 'Opt, DAR'. 
Line 865: Unknown card: 'Merfolk Trickster, DAR'. 
Line 878: Unknown card: 'Tiana, Ship's Caretaker, DAR'. 
Line 879: Unknown card: 'Aesthir Glider, DAR'. 
Line 882: Unknown card: 'Excavation Elephant, DAR'. 
Line 883: Unknown card: 'Blackblade Reforged, DAR'. 
Line 886: Unknown card: 'Dub, DAR'. 
Line 889: Unknown card: 'Llanowar Elves, DAR'. 
Line 892: Unknown card: 'Ghitu Journeymage, DAR'. 
Line 895: Unknown card: 'Frenzied Rage, DAR'. 
Line 902: Unknown card: 'Multani, Yavimaya's Avatar, DAR'. 
Line 904: Unknown card: 'Ghitu Lavarunner, DAR'. 
Line 905: Unknown card: 'Pierce the Sky, DAR'. 
Line 906: Unknown card: 'Firefist Adept, DAR'. 
Line 912: Unknown card: 'Fight with Fire, DAR'. 
Line 941: Unknown card: 'Caligo Skin-Witch, DAR'. 
Line 949: Unknown card: 'Invoke the Divine, DAR'.

**Comment by kelesi** [comment]
Fixed in [0.2.5](https://github.com/kelesi/mtga-utils/tree/0.2.5) and [build](https://github.com/kelesi/mtga-utils/releases/tag/0.2.5)
