### ISSUE TITLE
Core 2019 SetID Not Correct for a few cards

### ISSUE THREAD

**Issue by seannyfunco** [kelesi/mtga-utils#9]
Following cards should be listed with a setID of "M19"

Line 168: Unknown card: 'Immortal Phoenix, G18'. 
Line 535: Unknown card: 'Angelic Guardian, G18'. 
Line 637: Unknown card: 'Vengeant Vampire, G18'. 
Line 661: Unknown card: 'Rampaging Brontodon, G18'. 
Line 813: Unknown card: 'Angler Turtle, G18'.

**Comment by kelesi** [comment]
Thanks for reporting. Can you please provide the mtga ids of these cards from your collection?

**Comment by kelesi** [comment]
Seems like this is from ScryFall. G18 is "M19 Gift Pack" ([Vengeant Vampire](https://api.scryfall.com/cards/7dbd00dc-0d61-4960-8bc4-1b6ba34fc599?format=json&pretty=true))
The card is not in python-mtga. I will report this to them. In the meantime I will prepare a mapping from G18 to M19 in the ScryFall fetching.

**Comment by kelesi** [comment]
Scryfall workaround added in [0.2.5](https://github.com/kelesi/mtga-utils/tree/0.2.5) and [build](https://github.com/kelesi/mtga-utils/releases/tag/0.2.5).
Please check and let me know as I do not have these cards.

**Comment by seannyfunco** [comment]
Imports are now completing clean. Thanks for your help!
